pact-foundation/pact-reference

javascript/lib/simple_pact.js
javascript/lib/simple_pact_error.js

The basic run task only work with the following adjustment of the path.

Fix wrong path

---

rust/pact_matching/src/models/mod.rs
rust/pact_matching/tests/test_pact_camel_case_spec_version.json
rust/pact_matching/tests/tests.rs

Support for camel case format pact specifications

---

rust/pact_consumer/src/builders/http_part_builder.rs
rust/pact_consumer/src/builders/request_builder.rs
rust/pact_consumer/src/builders/response_builder.rs
rust/pact_consumer/src/test_support.rs
rust/pact_matching/src/models/mod.rs

Hi all
First time submitting a PR to this repo and first time writing Rust so please go easy on me.
This PR adds header_from_provider_state and path_from_provider_state functionality so that people can use ProviderState generators for these.

Added header_from_provider_state and path_from_provider_state

---

rust/pact_verifier/src/provider_client.rs

Fix https://github.com/pact-foundation/pact-js/issues/646
Issue explained more details in this comment https://github.com/pact-foundation/pact-js/issues/646#issuecomment-850831411
Hi maintainers,
I am brand new to Rust, so I am not sure I follow standard practice, please help to review and comments are welcome.

fix: correct headers attribute with multiple values might not be matched

---

rust/pact_verifier/src/provider_client.rs

test the `extract_headers` function. Specially when a comma separated list of values is given, see https://github.com/pact-foundation/pact-js/issues/646
CC @tonynguyenit18

test: extract_headers function, specially with comma separated values

---

rust/pact_ffi/src/verifier/handle.rs
rust/pact_ffi/src/verifier/mod.rs
rust/pact_verifier/src/callback_executors.rs

This is my first time writing and creating merge request in Rust

chore: add verifier ffi function update provider state

---

rust/Cargo.lock
rust/pact_consumer/Cargo.toml
rust/pact_ffi/Cargo.toml
rust/pact_mock_server/Cargo.toml
rust/pact_mock_server_cli/Cargo.toml
rust/pact_models/Cargo.toml
rust/pact_verifier/Cargo.toml
rust/pact_verifier_cli/Cargo.toml
rust/pact_verifier_cli/README.md

Added some docs to explain the benefits to the verifier.

feat: support native TLS. Fixes #144

---

php/pact/http-consumer-1-http-provider.json
php/pact/http-consumer-2-http-provider.json
php/pact/message-consumer-2-message-provider.json
php/public/proxy.php
php/src/consumer-1.php
php/src/consumer-2.php
php/src/provider.php
rust/pact_ffi/src/verifier/handle.rs
rust/pact_ffi/src/verifier/mod.rs

Depend on https://github.com/pact-foundation/pact-reference/pull/164

Update php examples

---

rust/pact_ffi/src/mock_server/bodies.rs

Generators detected via from_integration_json -> process_object were hard-coded to be body generators, when they may also apply to paths, headers and query strings. 
This change uses the matching rule category to determine where the generator should be stored.
I considered modifying the method signature, but felt this reduced the duplication in concepts. I don't believe there are cases where generator categories exist independent of their matching rules category so it should be safe.

fix: generators in process_object

---

rust/pact_verifier/src/lib.rs
rust/pact_verifier/src/tests.rs

As explained in #181, this should be possible.
This is my first time interacting with this codebase, so please let me know if there’s anything wrong with what I’ve implemented here and/or if there are other ways to check for regressions than `cargo test`.

Allow BrokerWithDynamicConfiguration to publish results

---

rust/pact_mock_server/src/hyper_server.rs

The `access-control-allow-origin` value was being sourced from the referrer, which resulted in a trailing `/` and caused CORS pre-flight requests to fail.
This change sources the allowed origin from `origin` header, ensures it's the same for cors responses pre and post the pre-flight request, and adds the `access-control-allow-credentials` header.
See also https://github.com/pact-foundation/pact-js/issues/943.

fix(cors): source allowed origin from origin header, add credentials

---

rust/pact_verifier/src/pact_broker.rs

This PR adds a [`User-Agent`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) to the `HALClient` used by the `pact_verifier` to interact with the Pact Broker.
Fixes #236.

feat: add user-agent header to the HALClient

---

rust/pact_ffi/release-linux.sh

requires latest cross fetched from git
closes #320
related https://github.com/cross-rs/cross/issues/1302

chore: renable aarch64-unknown-linux-gnu

---

rust/pact_ffi/src/mock_server/bodies.rs
rust/pact_ffi/src/mock_server/handles.rs
rust/pact_ffi/tests/tests.rs

Fix https://github.com/pact-foundation/pact-reference/issues/322

feat: Add ffi function pactffi_with_multipart_file_v2

---

rust/Cargo.lock
rust/pact_ffi/Cargo.toml
rust/pact_ffi/src/models/message.rs

Apply generators to `pactffi_message_get_contents`
For #338

feat: Apply generators to message's contents

---

rust/pact_matching/src/headers.rs
rust/pact_matching/src/matchers.rs

An attempt to fix https://github.com/pact-foundation/pact-reference/issues/331

fix(pact_matching): Allow matching strings using Values matcher

---

rust/pact_matching/src/json.rs

These tests describe weird behavior of `Values` matcher mentioned in #337
* The `Values` matcher is mentioned 2 times in the [specification](https://github.com/pact-foundation/pact-specification/tree/version-4#supported-matching-rules)
* About `Values` matcher itself: `Match the values in a map, ignoring the keys`
* About `EachValue` matcher: `... For maps, delgates to the Values matcher.`
* I have no clue how it should work, except it `ignoring the keys`
* I take a look at the code
* The code handling matching for `maps` and `lists` is a bit complicated.
* But I can see the `first value` play an important role. It explain why `missing values` is ok, `duplicated first value` is ok
* Look like the code for `Values` matcher is empty, so it's not implemented, but rely on a general code that …

test(pact_matching): Test Values matcher with json body

---

compatibility-suite/Cargo.lock
rust/pact_mock_server_cli/release-linux.sh
rust/pact_verifier_cli/release-linux.sh

Create musl based variants of 
- pact_verifier_cli
- pact_mock_server_cli
Tracking issue:- https://github.com/pact-foundation/devrel/issues/30
Follows on from #372

feat: musl verifier mock server cli

---

rust/pact_matching/src/json.rs
rust/pact_matching/src/matchingrules.rs
rust/pact_matching/src/query.rs
rust/pact_matching/src/tests.rs

* Add `compare_lists_with_matchingrules`
* Reuse `compare_lists_with_matchingrules` in `json`
* Support `ArrayContains` and `EachValue` matchers in `query` by using `compare_lists_with_matchingrules`

feat: Match query with ArrayContains and EachValue matchers

---

rust/pact_matching/src/headers.rs

* Use `compare_lists_with_matchingrules` inside a new `if` condition for `headers`

feat: Match headers with ArrayContains and EachValue matchers

---

rust/pact_ffi/src/mock_server/handles.rs

If the content type was not otherwise handled,
`OptionalBody::from(&str)` was used. This sets the content type associated with the body to `None` irrespective of the content type passed through to `process_body`.
This fixes the issue by ensuring the `OptionalBody::Present` is created with the appropriate content type.

fix(ffi): annotate body in raw body branch

---

rust/Cargo.lock
rust/pact_models/Cargo.toml
rust/pact_models/src/content_types.rs
rust/pact_models/src/generators/form_urlencoded.rs
rust/pact_models/src/generators/mod.rs

Implement for https://github.com/pact-foundation/roadmap/pull/99

feat: Support generators for form urlencoded

---

rust/pact_models/src/path_exp.rs

The test methods is clearly testing `matches_path`, but calling `path_weight`

fix: Fix test wrong method

---

rust/pact_models/src/matchingrules/expressions.rs

See related issue and pull request:
* https://github.com/pactflow/pact-protobuf-plugin/issues/191
* https://github.com/pact-foundation/pact-php/pull/735

feat: Support fromProviderState generator in regex matching expression
