pact-foundation/pact-reference

- rust/pact_matching/src/lib.rs
- rust/pact_matching/src/tests.rs
`Accept` and `Content-Type` headers now optionally accept parameter values if they are not specified in the expectation, but are enforced if they are specified. Resolves #1 
Also made mismatch messaging consistent when the fallback `EqualityMatcher` is used during header checks and plus tests.
> Added handling of optional parameters for 'Accept' and 'Content-Type' headers

- rust/pact_mock_server/src/lib.rs
As this function is intended for use from other languages I would suggest to return a simple String instead of a serde_json::Value type.
Thus I don't need to have serde_json as a dependency in my [wrapper library](https://github.com/elitau/pact_elixir).
> Return a String instead of a serde_json value

- rust/pact_matching/src/models/mod.rs
- rust/pact_matching/src/models/tests.rs
- rust/pact_matching/tests/test_pact_root_string_json.json
- rust/pact_matching/tests/tests.rs
When using JSON root value strings, the pact_matching library adds extra quotes to the string even if it already has them. 
Previous behaviour:
"example1" -> "\\\"example1\\\""
"\\\"example2\\\"" -> "\\\"\\\"example2\\"\\\""
This fix has just allowed both Strings and key-value HashMaps to pass as valid JSON.
> fix json body matcher so root value strings and key value pairs are both valid

- c/consumer-verification/src/main.c
- javascript/lib/simple_pact.js
- rust/pact_mock_server_ffi/src/lib.rs
This PR remove the "_ffi" suffix from `create_mock_server` that seems to be readd.
This PR also fix broken usage (javascript and c examples).
> Fix pack_mock_server C api and usage

- rust/pact_mock_server_ffi/src/lib.rs
It is currently not possible to create a mock server several times as the global logger will be initialize more than once.
> Allow to recreate mock-server

- rust/pact_verifier_cli/Cargo.toml
- rust/pact_verifier_cli/src/main.rs
I [commented](https://github.com/pact-foundation/pact-reference/pull/55#issuecomment-575983245) on the `pact_verifier_cli` problem you found. You're right, I had not actually tested running that executable. Here's what I believe is the fix. I have no deep explanation of how the fix works, it's just the first thing I thought of, and it seems to work.
> Make pact_verifier_cli actually runnable by using tokio::main

- rust/pact_verifier/src/callback_executors.rs
- rust/pact_verifier/src/lib.rs
- rust/pact_verifier/src/tests.rs
- rust/pact_verifier_cli/src/main.rs
This fixes a compilation failure in `pact_verifier_cli` due to a typechecking issue with a `None` variant of an `Option<F> where F: RequestFilterExecutor` by introducing a `NullRequestFilterExecutor` and annotating the `None` variant to have the type `Option<Box<NullRequestFilterExecutor>>`. This allows the crate to compile as expected, and does not change behavior.
Note that if `NullRequestFilterExecutor` is ever attempted to be called (unlike the current usage, where it is solely used as a type annotation) it will panic the current thread.
Approved …
> Fix RequestFilterExecutor w/ verify_provider

- rust/pact_matching/src/models/matchingrules.rs
- rust/pact_matching/src/models/message.rs
- rust/pact_matching/src/models/mod.rs
- rust/pact_matching/src/models/provider_states.rs
The v3 spec moves from `providerState` to `providerStates`, but the `Message` implementation in the Rust reference uses the old version. This fixes that, fixes broken documentation links, updates tests to the corrected API, and attempts to at least partially correct the broken auto-derived `Serialize` and `Deserialize` impls (see commit description on that commit for more info).
Approved for Public Release; Distribution Unlimited. Case Number 19-3203.
(c) 2020 The MITRE Corporation. All Rights Reserved.
> Fix v3 Message Provider States

- rust/pact_verifier/src/provider_client.rs
- rust/pact_verifier_cli/src/args.rs
`Error::description` is deprecated as of Rust 1.42:
https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#error:description-is-deprecated
Approved for Public Release; Distribution Unlimited. Case Number 19-3203.
(c) 2020 The MITRE Corporation. All Rights Reserved.
> Avoid deprecated Error::description in favor of Display trait

- .travis.yml
Currently, Travis CI is slowed down by needing to re-process dependencies every time it runs. Per the [Travis documentation](https://docs.travis-ci.com/user/languages/rust/#dependency-management), adding `cache: cargo` to the `.travis.yml` file will reuse dependencies and should speed up CI runs.
Approved for Public Release; Distribution Unlimited. Case Number 19-3203.
(c) 2020 The MITRE Corporation. All Rights Reserved.
> Teach Travis CI to cache Cargo dependencies

- rust/pact_mock_server/src/mock_server.rs
Writes the pact with the current Pact version, instead of hard coding to V3.
> fix: write_pact_file  always serialising a v3 pacts

- rust/pact_matching/src/models/message_pact.rs
- rust/pact_matching/src/models/mod.rs
This adds an initial implementation of a Message Pact from the v3 spec.
MITRE plans to use this in the near future via FFI to support a basic Pact provider testing capability for message-based services written in C++.
This implementation is missing `merge()`.
Since `merge()` is missing, no method is provided to write a MessagePact to disk and attempt to merge it.
Instead, `overwrite_pact()` is included, which just overwrites a file if it is present.
An additional `merge_pact()` method could be added later.
Approved for Public Release; Distribution …
> Add MessagePact (Pact with Messages instead of Interactions)

- rust/pact_verifier/src/messages.rs
This is a minor change that sets the `Content-Type` http header to `application-json` when sending POST requests to the provider to run the verification process against its messages.
The lack of that header caused some (albeit minor) annoyances in one of our projects, as the library we used to expose the verification endpoint would not automatically parse the body of the request when the header is missing.
I found no tests relevant to this behavior, therefore I only tested this change manually. Please let me know if I missed anything.
Also, I haven't found any guidelines for contributing, so in case I did anything wrong please let me know :)
Thanks!
> Set content-type header in message request to provider

- rust/pact_mock_server_ffi/src/lib.rs
Adds a `*char version()` c interface to the mock server FFI, for use with detecting compatible client versions.
NOTE: I originally added it as a `*const  c_char` but it then required freeing via the usual c call. I think this consistency is nicer.
> feat: return version of the mock server via FFI

- rust/pact_matching/src/models/mod.rs
- rust/pact_matching/src/models/tests.rs
Request headers are serialised in a hashmap; serializing and deserializing rust hashmaps can change the internal order of keys in the hashmap. 
This can confuse the Request::differences_from code, which sees out-of-order keys as different. 
Sorting the keys before comparison fixes the problem.
> fix: request headers generated unexpected differences 

- rust/Cargo.lock
- rust/pact_consumer/Cargo.toml
- rust/pact_mock_server/Cargo.toml
- rust/pact_mock_server_cli/Cargo.toml
- rust/pact_mock_server_ffi/Cargo.toml
Found some more outdated crate versions. No hurry to make a new release.
> chore: upgrade maplit, itertools

- rust/pact_verifier/src/callback_executors.rs
- rust/pact_verifier/src/tests.rs
Given this state from the `providerStates` key in the pact:
i.e. I was expecting something to mirror this:
```
{
"name": "User foo exists",
"params": {
"some": "param"
}
}
```
The current state change process for FFI / CLI sends the following message to the pact client to instruct it to prepare a state:
```
{ "action": "teardown", "some": "param", "state": "User foo exists" }
```
I encountered two issues with this:
1. Note the parameters aren't self-contained for simple extraction to pass to a user provided function. Not having a clear top-level structure made the JSON marshaller a bit confused, so extra work was required to separate the "framework" part from the "user supplied data"
2. If a user wants to use the keys `state` or `action` we'll have a conflict
I'm proposing that we move …
> fix: move state params to "params" key in provider state change executor

- rust/Cargo.lock
- rust/pact_matching/Cargo.toml
- rust/pact_matching/src/models/file_utils.rs
- rust/pact_matching/src/models/message_pact.rs
- rust/pact_matching/src/models/mod.rs
- rust/pact_matching/src/models/v4/mod.rs
- rust/pact_mock_server/Cargo.toml
- rust/pact_mock_server/src/mock_server.rs
- rust/pact_verifier/Cargo.toml
- rust/pact_verifier/src/lib.rs
- Add a dependency on the `anyhow` library.
- Replace `io::Result` with `anyhow::Result` in functions that can return multiple types of error.
- Refactor `load_pact_from_url` and `load_pact_from_json` to use `?` operator instead of pattern matching.
Approved for Public Release; Distribution Unlimited. Case Number 19-3203.
(c) 2021 The MITRE Corporation. All Rights Reserved.
> refactor: Use Anyhow instead of `io::Result`

- rust/pact_mock_server_ffi/src/lib.rs
- rust/pact_models/src/lib.rs
This allows for clients to build multi version compatible interfaces via the FFI bindings.
I wasn't so sure about creating a new enum for the `SpecificationVersion` that is exposed to the c interface.
Alternatively, we could expose the underlying `PactSpecification` enum. Let me know what you prefer.
> feat: allow ffi bindings to set spec version

- rust/Cargo.lock
- rust/pact_matching/src/lib.rs
- rust/pact_matching/src/models/message.rs
- rust/pact_matching/src/models/message_pact.rs
- rust/pact_matching/src/models/v4/mod.rs
- rust/pact_matching_ffi/src/models/message.rs
- rust/pact_mock_server_ffi/src/lib.rs
- rust/pact_verifier/Cargo.toml
- rust/pact_verifier/src/messages.rs
- rust/pact_verifier/src/provider_client.rs
- rust/pact_verifier_cli/README.md
There is currently no way to pass metadata back to the (HTTP based) verifier, for use by the command line or FFI interface.
This PR adds that.
1. I noticed the verifier doesn't read the `metadata` section (still uses `metaData` when reading a Pact) but generates a pact with `metadata`. It now reads both for compatibility
2. The incoming payload now supports a header (`PACT_MESSAGE_METADATA`) that accepts a base64 encoded JSON of key/value pairs. The values may be complex JSON objects, or simple primitives
3. The `metadata` property of the `Message` struct, now supports complex values to support this.
> Support verifying message metadata via verifier (CLI/FFI)

- rust/pact_mock_server_ffi/src/lib.rs
See also #118.
I went with `log_message` instead of `log` because Golang warned that it conflicted with default libraries on a Mac, so felt it was best to avoid a general term.
> feat: allow callers to add messages to log

- rust/pact_matching/src/lib.rs
- rust/pact_models/src/generators.rs
- rust/pact_models/src/interaction.rs
- rust/pact_models/src/matchingrules.rs
- rust/pact_models/src/message.rs
- rust/pact_models/src/pact.rs
- rust/pact_models/src/path_exp.rs
- rust/pact_models/src/request.rs
- rust/pact_models/src/response.rs
- rust/pact_models/src/sync_interaction.rs
- rust/pact_models/src/sync_pact.rs
- rust/pact_models/src/tests.rs
- rust/pact_models/src/v4/async_message.rs
- rust/pact_models/src/v4/http_parts.rs
- rust/pact_models/src/v4/message_parts.rs
- rust/pact_models/src/v4/synch_http.rs
- rust/pact_verifier/src/pact_broker.rs
This Pull Request is in preparation for the upcoming PR about path expressions.
1. refactor: Move path expression functions into `path_exp` module
Specifically: `matches_token`, `calc_path_weight`, and `path_length`.
2. refactor: Make many JSON parsing functions fallible
This is in preparation for an upcoming change that will cause `parse_path_exp` to be called during JSON parse time.
There are now error messages for MatchingRule parsing.
Errors during MatchingRule parsing will now cause JSON parsing to fail overall, rather than just printing a warning.
Errors parsing the status code in a StatusCode matcher will also cause JSON parsing to fail overall, rather than just printing an error.
This software was produced for the U. S. Government under Contract No. FA8702-20-C-0001, and is …
> refactor: Move path functions, and make JSON parsing fallible

- rust/pact_consumer/src/builders/http_part_builder.rs
- rust/pact_consumer/src/builders/request_builder.rs
- rust/pact_consumer/src/patterns/date_time.rs
- rust/pact_consumer/src/patterns/json_pattern.rs
- rust/pact_consumer/src/patterns/mod.rs
- rust/pact_consumer/src/patterns/special_rules.rs
- rust/pact_consumer/src/patterns/string_pattern.rs
- rust/pact_consumer/src/util.rs
- rust/pact_ffi/src/mock_server/bodies.rs
- rust/pact_ffi/src/mock_server/mod.rs
- rust/pact_matching/src/generator_tests.rs
- rust/pact_matching/src/generators.rs
- rust/pact_matching/src/lib.rs
- rust/pact_models/src/generators.rs
- rust/pact_models/src/http_parts.rs
- rust/pact_models/src/matchingrules.rs
- rust/pact_models/src/path_exp.rs
- DocPaths are eagerly parsed into tokens, instead of lazily at usage time.
- Headers and Query parameters are parsed into DocPaths, and the first Field token is extracted to recover the plain string.
- Many functions now take `DocPath` instead of `&str`.  This might be considered a breaking change.
- Errors when parsing DocPaths will now be fatal errors during the parsing of Pact JSON structures.  This might be considered a breaking change.
- Moved `fn obj_key_for_path` from the `pact_consumer` crate into `path_exp`.
- Deleted now-obsolete tests for generators handling invalid expressions.
- (Code Style) Split function signatures and invocations into multiple lines and added trailing commas, where changes were already being made.
This software was produced for the U. S. Government under …
> refactor: Introduce DocPath struct for path expressions

- rust/Cargo.lock
- rust/pact_matching/Cargo.toml
This upgrades all of `nom` to `7.0.0`.
In order to pass tests, the `with-gpl-data` feature needed to be added. `tree_magic_mini` is GPL-licensed, because [the MIME database is](https://github.com/mbrubeck/tree_magic#licensing-and-the-mime-database). Which in turn makes pact-reference itself GPL.
Note that tree_magic_mini is already GPL-licensed at [version 2](https://github.com/mbrubeck/tree_magic/blob/mini/CHANGELOG.md).
> chore: upgrade tree_magic_mini to 3.0.1

- rust/pact_ffi/src/mock_server/handles.rs
- rust/pact_ffi/tests/tests.rs
I have small pact acceptance suite in Pact Go that tests that go can call the main FFI methods.
The one that runs through a basic lifecycle is producing this pact file:
```json
{
"consumer": {
"name": "test-http-consumer"
},
"interactions": [
{
"description": "some interaction",
"key": "8369cdf3b43ff542",
"pending": false,
"providerStates": [
{
"name": "some state"
}
],
"request": {
"method": "GET",
"path": "/products"
},
"response": {
"body": {
"content": "{\"age\":23,\"alive\":true,\"name\":\"some name\"}",
"contentType": "*/*",
"encoded": false
},
"headers": {
"Content-Type": [
"application/json"
]
},
"matchingRules": {
"body": {
"$.name": {
"combine": "AND",
"matchers": [
{
"match": "type"
}
]
}
}
},
"status": 200
},
"type": "Synchronous/HTTP"
}
],
"metadata": {
"pactRust": {
"ffi": …
```
> fix: FFI always detects + stores JSON bodies as plain text

- rust/pact_ffi/src/verifier/handle.rs
- rust/pact_ffi/src/verifier/mod.rs
- rust/pact_ffi/src/verifier/verifier.rs
- rust/pact_verifier/src/lib.rs
- rust/pact_verifier/src/tests.rs
- rust/pact_verifier_cli/src/main.rs
This change makes the verifier FFI easier to work with because the publishing options are split from the verification options.
The verification options should apply to all pact sources (such as file and URL) because they contain global settings such as request timeouts and callbacks.
However, the publish options only make sense when a Pact Broker is configured. This made the FFI tricky to use from library code (in particular from PactNet) because that meant you could only set the global verification options when using a Pact Broker source, instead of when using any source. This change will allow that happen properly in future.
As an aside, I didn't find any unit tests to update at all for this, which is a bit concerning.
> feat(ffi)!: Separate verification and publishing options

- rust/pact_ffi/src/verifier/handle.rs
- rust/pact_ffi/src/verifier/mod.rs
The user has to specify `provider_name` as part of the `set_provider_info` call, so we can reuse that name when adding a broker source instead of forcing the user to supply it again.
> feat(ffi)!: Remove the need to repeat the provider name in verifier FFI

- rust/pact_ffi/src/verifier/args.rs
- rust/pact_verifier_cli/src/args.rs
Fixes https://github.com/pact-foundation/pact-js/issues/761
Alternatively, could just make `integer_value` a 64bit number and not worry too much about restricting the port range.
> fix: provider request timeout should be > 16bit integers. 

- rust/pact_ffi/src/mock_server/handles.rs
Matching rules were incorrectly being serialised to the request body matching rules section.
See also https://pact-foundation.slack.com/archives/C9VBGLUM9/p1646804259107749.
> fix: xml response matching rules

- rust/pact_matching/Cargo.toml
- rust/pact_models/Cargo.toml
This solves https://github.com/rustsec/advisory-db/blob/main/crates/time/RUSTSEC-2020-0071.md
> Removed dependency on time v0.1

- rust/pact_verifier_cli/src/main.rs
Fixes: https://github.com/pact-foundation/pact-reference/issues/217
> fix(pact_verifier_cli): stop using deprecated clap::parser::matches::arg_matches::ArgMatches::values_of_lossy

- rust/Cargo.lock
- rust/pact_models/Cargo.toml
- rust/pact_models/src/generators/mod.rs
I added a fast path for adding new nodes with `indextree` - https://github.com/saschagrunert/indextree/pull/92.
From a glimpse at this project I'm guessing perf isn't important, but maybe you'll still be interested in this tiny refactor.
> refactor: bump indextree, use append_value()

- .cirrus.yml
- rust/pact_mock_server_cli/release-osx.sh
- Add aarch64-apple-darwin target for pact_mock_server_cli
- Adds smoke test for  aarch64-apple-darwin target for pact_mock_server_cli
Bonus
- Adds smoke test for  aarch64-apple-darwin target for pact_mock_server_cli
- Adds smoke test for  aarch64-unknown-linux-gnu target for pact_verifier_cli
- Adds smoke test for  aarch64-unknown-linux-gnu target for pact_verifier_cli
| OS           | Architecture | Supported |
| ------- | ------------ | --------- |
| OSX        | x86_64       | ✅         |
| OSX        | aarch64 (arm)| ✅         |
| Linux    | x86_64       | ✅         |
| Linux    | aarch64 (arm)| ✅         |
| Windows    | x86_64  | ✅         | 
CI can be run locally with [tart.run](https://tart.run/) and [cirrus-cli](https://github.com/cirruslabs/cirrus-cli) on a mac machine with …
> feat: pact_mock_server_cli osx aarch64

- .github/workflows/build-ffi.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- rust/pact_ffi/CMakeLists.txt
- rust/pact_ffi/ci-build.sh
- rust/pact_ffi/release-linux.sh
Hey @uglyog 
Noted the CI workflows were throwing a few deprecation notices, and the release workflow was failing on any jobs that were for the ffi, verifier cli, or mock server cli, so this PR add's a few changes to clean up the build
1. Update `actions/checkout@v2` to `actions/checkout@v3`
2. Switch deprecated `actions-rs/toolchain@v1` with `dtolnay/rust-toolchain` https://github.com/dtolnay/rust-toolchain as original unmaintained - see [issue](https://github.com/actions-rs/toolchain/issues/216) 
3. Replace `marcopolo/cargo@master` also unmaintained, and not sure using an action for this adds value based on what we are using from it, with a cargo rust/test/build and setting the `working-directory` as part of the gh action step value
4. Remove `choco install -y llvm` from windows …
> ci(chore) - various updates to replace deprecated action notices and red builds

- rust/pact_ffi/tests/tests.rs
- rust/pact_verifier/src/lib.rs
Fix https://github.com/pact-foundation/pact-plugins/issues/44
~~I don't know how to write test for this. Please show me how if it's required.~~ I guess the 'missing plugin' test is enough to cover this change?
> fix(pact_verifier): Fix missing PATCH version in plugin's version

- rust/pact_ffi/src/matching.rs
- rust/pact_matching/src/matchers.rs
Fix https://github.com/pact-foundation/pact-reference/issues/318
> fix: Allow matching string values using content type matching rule

- rust/pact_models/src/generators/mod.rs
Remove the errors similar to `Could not generate a random decimal from null`.
It then allow to use integration json like this:
```
{
"pact:matcher:type": "null",
"pact:generator:type": "RandomDecimal"
}
```
This change is for implementing compatibility suite in pact-php (and probably other languages that use FFI calls as well).
For more information, please take a look at this [discussion](https://pact-foundation.slack.com/archives/C02BXLDJ7JR/p1698980611664139)
> fix: Fallback to always generate a value to fix 'Could not generate a random TYPE from null'

- rust/pact_ffi/src/models/message.rs
Apply generators to `pactffi_message_metadata_iter_next`
Please review https://github.com/pact-foundation/pact-reference/pull/340 first
For #338
> feat: Apply generators to message's metadata

- rust/pact_ffi/src/mock_server/handles.rs
Apply generators to `pactffi_message_reify`
Please review #341 first
For #338
> feat: Apply generators to message's contents and metadata

- rust/pact_ffi/src/mock_server/handles.rs
- rust/pact_ffi/tests/tests.rs
Allow setting matchers and generators to metadata with new FFI call `pactffi_message_with_metadata_v2`
Please review #342 first
This is for the scenario [Supports the use of generators with message metadata](https://github.com/pact-foundation/pact-compatibility-suite/blob/main/features/V3/message_consumer.feature#L71-L78)  in compatibility suite
> feat: Add pactffi_message_with_metadata_v2

- rust/pact_ffi/src/mock_server/bodies.rs
- rust/pact_ffi/src/mock_server/handles.rs
Reuse code to:
* Support nested matching rules and generators instead of single level
* Support any types for metadata's value, not just string
* Fix `null` when `pact:matcher:type` is not set in JSON object e.g. `JSON: { "ID": "sjhdjkshsdjh", "weight": 100.5 }`
> refactor: Reuse matching rules and generators processing code

- rust/pact_ffi/src/matching.rs
- rust/pact_matching/src/json.rs
- rust/pact_matching/src/matchers.rs
I added `pactffi_matches_string_value_using_content_type_matching_rule_test` before, but it only test 2 cases but need a lot lines of code.
I found a shorter way to test, so I refactor + add more cases to it.
> test(pact_matching): Test more cases for ContentType matcher

- rust/pact_ffi/release-win.sh
- rust/pact_mock_server_cli/release-win.sh
- rust/pact_verifier_cli/release-win.sh
fixes #325 
Previously this was failing without a work-around due to an issue in ring 16.x but it has since been updated to use ring 17.x and CI builds successfully for all three of our distributed executables/libraries
> feat: build aarch64-pc-windows-msvc target (ffi/mock_server/verifier)

- rust/pact_ffi/release-linux.sh
- rust/pact_ffi/release-osx.sh
- rust/pact_mock_server_cli/release-linux.sh
- rust/pact_verifier_cli/release-linux.sh
Appears to build correctly when pinning to Cross 0.2.5
> chore: renable verifier aarch64 linux

- rust/pact_ffi/release-linux.sh
- rust/pact_ffi/release-osx.sh
- rust/pact_mock_server_cli/release-linux.sh
- rust/pact_verifier_cli/release-linux.sh
fixes #354 
Cross was being retrieved from main for aarch64 linux targets, which compiles against 2.31 of glibc.
Pinning cross to 0.2.5 will result in an image using 2.23 glibc which you can see by running `ldd --version` 
It can be confirmed, and checked easily against different image tags using the following in the `Cross.toml`
```toml
[target.aarch64-unknown-linux-gnu]
pre-build=[
"ldd --version",
"exit 1",
]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5"
```
This PR also introduces a `cargo clean` command in between builds in order to not impact issues in builds (spurious glibc errors)
> fix: pin cross to 0.2.5 for glibc 2.23

- rust/pact_ffi/release-linux.sh
One change didn't make the cut when I split my changes into multiple PR's meaning the aarch64 musl artifacts are generated but missing from the release
> chore: update artifact path for aarch64 musl pact_ffi

- rust/pact_verifier/src/lib.rs
Provider name is optional, and default value is 'provider'.
When verifier is configured without provider name (probably new user not knowing it, or forget about it), and there is (high chance that) no provider has the name 'provider', verifier print this message:
`No pacts found matching the given consumer version selectors in pact broker`
This message is not wrong, but it is hard to debug in this situation
> feat: Print provider name in 'no pacts found' message to help debugging

- rust/pact_matching/src/json.rs
- rust/pact_matching/src/matchingrules.rs
The old error message is a little bit confusing:
`Expected data to have a content type of 'text/html' but was Expected binary contents to have content type 'text/html' but detected contents was 'text/plain'`
The updated one will be:
`Failed to match data to have a content type of 'text/html': Expected binary contents to have content type 'text/html' but detected contents was 'text/plain'`
> feat: Rephrase the content type matching error message

- rust/pact_ffi/src/mock_server/handles.rs
While it is already possible to add matching rules through the various other methods, it was not possible to add a matching rule directly. This adds a new `with_matching_rules` FFI function.
This was inspired by the implementation of the V2 compatibility suite in Pact Python.
> feat(ffi): add with_matching_rules

- compatibility-suite/Cargo.lock
- rust/pact_consumer/src/builders/sync_message_builder.rs
This PR fixes an issue where metadata matching rules were not stored in the pact file. 
First time writing any rust code, please let me know if something is not idiomatic or optimal.
> Support metadata rules for sync message

- .github/workflows/release.yml
- rust/pact_ffi/release-linux.sh
This allows client libraries which only provide the ability to load dynamically shared libraries `*.so` to utilise the pact ffi functionality.
Tested in Ruby, PHP and .NET as part of https://github.com/pact-foundation/devrel/issues/30
This PR also builds the x86_64 musl artifact with cross 0.2.5 as per the aarch64 musl artifact. I'm happy to remove this if required, but it seems to make sense to align them across our artifacts if they build.
Happy to make any changes or take anything out
> feat: convert musl static .a to .so

- rust/pact_ffi/src/mock_server/handles.rs
- rust/pact_ffi/tests/tests.rs
Add three new FFI methods:
- `pactffi_set_key(interaction: InteractionHandle, value: &const c_char)`
- `pactffi_set_pending(interaction: InteractionHandle: pending: bool)`
- `pactffi_set_comment(interaction: interactionHandle, key: &const c_char, value: &const c_char)`
These update an interactions key, pending status, and comments respectively.
While implementing the HTTP Consumer V4 compatibility suite, I realise there was no straightforward way to update these attributes of an interaction.
This pull request primarily focuses on enhancing the interaction handling capabilities in the `rust/pact_ffi` library. The changes include the addition of new functions to set key attributes, mark interactions as pending, and add comments to interactions. The tests have also been updated to reflect …
> [FFI] Functions for v4/http_consumer compatibility suite

- .github/workflows/release.yml
github action runner images appear to have been updated and despite mentioning xcode 12.4 in the runner image readme
https://github.com/actions/runner-images/blob/macOS-11/20240127.1/images/macos/macos-11-Readme.md#xcode
It is no longer being found and causes x86_64 builds for macos to fail
Relates to #391 
Has been tested in my fork (albeit with additional changes to pull in the musl aware version of the pact-plugin-driver, updated index and some tweaks to reduce the size of the output binaries)
https://github.com/YOU54F/pact-reference/releases/tag/libpact_ffi-v0.4.18
> ci(fix): add setup-xcode action to pin to 12.4

- rust/pact_matching/src/json.rs
- rust/pact_matching/src/lib.rs
- rust/pact_matching/src/matchers.rs
- rust/pact_matching/src/matchingrules.rs
To allow reusing `compare_lists_with_matchingrule`, to allow using `ArrayContains` and `EachValue` matchers for `query` and `headers`
* Add struct `CommonMismatch` (please suggest better name)
* Apply generic to `merge_result`
* Replace `Mismatch::BodyMismatch` to `CommonMismatch` on some places
> refactor: Replace Mismatch by CommonMismatch

- rust/pact_ffi/src/mock_server/handles.rs
There's a subtle lifetime issue created in the original code. The original code uses:
- `Bytes::from(&'static [u8])`
- `from_raw_parts<'a, T>(*const T, usize) -> &'a [T]`
Which requires the `*const T` pointer be a static pointer. Being provided through the FFI, this is unreasonable, and we should expect it to last only as long as the function call itself.
By simply replacing `Bytes::from` with `Bytes::from_from_slice`, we narrow down the lifetime from `'static` to `'a`, allowing for the underlying `*const T` pointer to be deallocated once the function has returned.
> fix: binary body lifetime issue

- .github/workflows/release.yml
Fix an issue resulting in no artifacts being uploaded to the release. The issue is two-fold:
- The `download-artifact` action by default, when there are multiple sources, is to extract each artifact in its own subdirectory.
- The `upload-release-action` only matches for files in the `rust/release_artifacts` directory, and importantly not any subdirectory.
The fix here is to simply toggle the `merge-multiple` to prevent artifacts from being extracted into separate subdirectories.
> chore(ci): fix upload

- rust/pact_ffi/src/mock_server/handles.rs
- rust/pact_ffi/tests/tests.rs
While the addition of `set_comment` allows for the comments to be used as per the Pact specification, it did not follow the original intent for comments (see the discussion in pact-foundation/pact-compatibility-suite#8).
The new `add_text_comment` function allows comments to be added repeatedly and appended into an array as intended in pact-foundation/pact-specification#45.
> feat(ffi): add `add_text_comment`

- rust/pact_models/src/headers.rs
User agents can and do contain commas, so they shouldn’t be split. Included is a test using the UA of my current browser.
> Parse user-agent as single value headers

- .github/workflows/build-ffi.yml
- .github/workflows/build.yml
- rust/Cross.toml
- rust/pact_ffi/release-linux.sh
use cross 0.2.5 to build `x86_64-unknown-linux-gnu`
cargo clean prior to building
pr to trigger release workflow
fixes https://github.com/pact-foundation/pact-js-core/issues/502
> chore: build linux x86_64 ffi against glibc 2.23

- rust/pact_consumer/src/patterns/special_rules.rs
Correct the example regex used for the `term!` and `matching_regex!` docs, and remove an accidental copy-pasta from the comment string in the example.
Fixes #424
> Correct term! documentation

- .github/workflows/build-ffi.yml
- .github/workflows/build.yml
- .github/workflows/compatability-suite.yml
- compatibility-suite/Cargo.lock
- compatibility-suite/pact-compatibility-suite/features/V3/matching_rules.feature
- rust/Cargo.lock
- rust/pact_consumer/Cargo.toml
- rust/pact_ffi/Cargo.toml
- rust/pact_ffi/src/matching.rs
- rust/pact_ffi/tests/tests.rs
- rust/pact_matching/Cargo.toml
- rust/pact_matching/README.md
- rust/pact_matching/src/binary_utils.rs
- rust/pact_matching/src/json.rs
- rust/pact_matching/src/matchers.rs
- rust/pact_matching/src/tests.rs
- rust/pact_models/src/v4/http_parts.rs
- rust/pact_models/src/v4/mod.rs
fixes #171 
`pact_matching` now performs the following for matching Binary content-types
1. Determines `expected` `Content-Type` header requested by user in test
2. Read content buffer with `infer` library, and guess `Content-Type` based on magic bytes
3. If unsuccessful
1. Read content buffer with `tree_magic_mini` library, and guess `Content-Type` based on shared-mime-info DB
1. MagicDB is not shipped with pact_matching, due to GPL restrictions, users can add manually
1. Linux Alpine - `apk add shared-mime-info`
2. MacOS `brew install shared-mime-info`
1. `arm64` MacOS requires `tree_magic_mini` [fork](https://github.com/you54f/tree_magic) 
3. Linux - Debian`apt-get install -y shared-mime-info`
4. If either result returns `text/plain`, then manually read bytes using …
> feat: update content_type_matching logic for binary payloads

- rust/Cargo.lock
- rust/pact_verifier_cli/Cargo.toml
- rust/pact_verifier_cli/src/reports.rs
When coloured output is enabled, output strings contain ANSI escapes, sequences of binary data that communicate with a terminal to control colours. Remove these sequences when producing a JUnit report, because the ESC bytecode (0x1B) is not a valid codepoint in XML documents.
Fixes #421
> Strip ANSI escapes from JUnit output

- .github/workflows/release.yml
- ruby/detect_os.rb
- ruby/smoke-test.sh
- ruby/test_ffi.rb
- rust/pact_ffi/release-linux.sh
- rust/pact_ffi/release-macos.sh
- rust/pact_ffi/release-win.sh
- rust/pact_verifier_cli/release-linux.sh
- rust/pact_verifier_cli/release-macos.sh
- rust/pact_verifier_cli/release-win.sh
- rust/scripts/gzip-and-sum.sh
Building individual targets allows us to identify where a single one fails, and gives us quicker feedback.
This mitigates some of the issues seen when building multiple targets with cross (wrong linker symbols), and allows us to enable per target caching which improves compile times.
Few other quality of life improvements are included (cron job, smoke test to weed out loading issues with the shared libraries)
- update release workflow to support
- workflow_dispatch
- cron schedule every wednesday
- run each target in seperate job
- add cache key per target
- update release scripts (pact_ffi / verifier_cli )
- allow building individual targets
- refactor similar steps
- generate musl .so with `RUSTFLAGS="-C target-feature=-crt-static"` fixes #436 
- smoke test dynamic lib loading (for …
> chore(ci): refactor indiv jobs

- rust/pact_verifier/src/pact_broker.rs
- rust/pact_verifier/src/selectors.rs
fixes #195 - also documents consumer version selector options as per pact broker docs
> feat(verifier): support fallback_branch consumer version selector

- rust/pact_ffi/src/mock_server/handles.rs
Add the ability to set metadata for sync and async message interactions. This capability was formerly provided with `message_with_metadata` using a `MessageHandle`; however, this is now deprecated in favour of the `InteractionHandle` method.
> feat(ffi): add with_metadata

- rust/pact_ffi/src/mock_server/handles.rs
- rust/pact_ffi/src/models/iterators.rs
Add a new V4 asynchronous message iterator. This mirrors the existing `pact_handle_get_sync_message_iter` and `pact_handle_get_http_iter`, and is the V4 counterpart for `pact_handle_get_message_iter`.
I have not marked the `pact_handle_get_message_iter` as deprecated; however, if the functionality of the new iterator supplants the older `PactMessageIterator`, it may be worth documenting the deprecation and directing people to use the new function/iterator.
PS: I have not written tests for it, but it would appear that the other iterators don't have tests either.
> feat(ffi): add async message iterator

- rust/pact_ffi/src/mock_server/handles.rs
Add FFI to add generators without requiring the use of integration JSON.
> feat: add with_generators

- rust/pact_ffi/src/models/async_message.rs
- rust/pact_ffi/src/models/contents.rs
- rust/pact_ffi/src/models/sync_message.rs
The various `get_contents` FFI method return the raw (unprocessed) contents of the request/response, including all generators and matching rules. The `generate_contents` alternatives are used to process these generators so that the actual messages as received by the consumer can be retrieved.
> feat: add `generate_contents` methods

- rust/pact_matching/src/lib.rs
The additional noise in the logs at `info` level is not needed and interferes with standard out (e.g. test output), and is more appropriate for `debug` level.
> fix: reduce log level for matching to debug

- rust/pact_ffi/src/mock_server/handles.rs
The logic of processing the body within the `pactffi_with_body` was not consistent across the various interaction types. This refactors the logic out into a separate `process_body` function.
Note that as a result of this change, the behaviour of the FFI _may_ change.
> fix(ffi): shared processing of body

- rust/pact_ffi/src/mock_server/handles.rs
The `pactffi_with_binary_file` is functionally replaced by the combination of `pactffi_with_binary_body` and
`pactffi_with_matching_ruless`. These two functions should be preferred over this one.
Furthermore, this function's naming (especially when compared to `pactffi_with_binary_body`) which might suggest it merely sets the body by reading a specific binary file.
> chore(ffi): deprecate `pactffi_with_binary_file`

- rust/pact_ffi/src/mock_server/handles.rs
* `pactffi_set_comment`
* `key` is not nullable
* `value` is nullable
* `pactffi_add_text_comment`
* `comment` is not nullable
> docs: Update safety comments

- rust/pact_ffi/src/mock_server/handles.rs
Copy comment from `pactffi_given_with_param` that mention parameter's value parsed as JSON
> docs: Update comment for pactffi_message_given_with_param

- rust/pact_matching/src/matchingrules.rs
- rust/pact_matching/src/query.rs
Before the fix:
```
2024-09-06T04:24:10.924510Z DEBUG tokio-runtime-worker pact_matching: --> Mismatches: [BodyMismatch { path: "$.$.age", expected: Some(b"[\"27\"]"), actual: Some(b"[\"41\"]"), mismatch: "Unable to match [\"27\"] using Number" }]
```
After the fix:
```
2024-09-06T04:18:29.737113Z DEBUG tokio-runtime-worker pact_matching::matchingrules: Comparing '["27"]' to '["41"]' using Number -> Ok(())
2024-09-06T04:18:29.737122Z DEBUG tokio-runtime-worker pact_matching::matchingrules: Comparing list item 0 with value 'Some("41")' to '"27"'
2024-09-06T04:18:29.737147Z DEBUG tokio-runtime-worker pact_matching::matchers: String -> String: comparing '27' to '41' ==> true cascaded=true matcher=Number
```
> fix: Fix can't match array of numbers

- rust/pact_consumer/src/patterns/special_rules.rs
- rust/pact_models/src/matchingrules/expressions.rs
- rust/pact_models/src/matchingrules/mod.rs
Given this test:
```rust
#[test]
fn each_value_matching_rule_comparation_test() {
assert_eq!(
matchingrules_list!{"body"; "$.array_values" => [MatchingRule::EachValue(MatchingRuleDefinition::new("[\"string value\"]".to_string(), ValueType::Unknown, MatchingRule::Type, None))]},
matchingrules_list!{"body"; "$.array_values" => [MatchingRule::EachValue(MatchingRuleDefinition::new("[\"something else\"]".to_string(), ValueType::Unknown, MatchingRule::Type, None))]}
)
}
```
Without the fix, this test will pass
With the fix, this test will failed with:
```
---- mock_server::bodies::test::each_value_matching_rule_comparation_test stdout ----
thread 'mock_server::bodies::test::each_value_matching_rule_comparation_test' panicked at pact_ffi/src/mock_server/bodies.rs:1133:5:
assertion failed: `(left …
```
> fix: Fix can't compare 2 eachKey matching rules, 2 eachValue matching rules

- rust/pact_verifier/src/pact_broker.rs
Fixes 406 Not Acceptable on publishing verification results, when using a pact broker started with thin. (puma / webrick do not exhibit the issue
> fix(verifier): add Accept-Charset=utf8 header when post/put

- .github/workflows/build-ffi.yml
- .github/workflows/build.yml
- .github/workflows/compatability-suite.yml
- .github/workflows/release.yml
This should help reduce the CI usage by:
1. Only running  CI on either:
- PRs targetting `master`
- pushes to `master`
Most importantly, CI is no longer doubled in PRs (as previously, `push` and `pull_request` would _both_ be triggered, consuming double the number of runners).
2. Cancelling existing runs if a new commit is added
3. Speeding up some existing builds by not unnecessarily rebuilding everything (especially with the compatibility suite)
4. Using nextest in place of `cargo test` as it is typically faster
5. Using caching of build dependencies where possible
> chore: reduce ci usage

- rust/pact_matching/Cargo.toml
- rust/pact_matching/src/generators/bodies.rs
Implement for https://github.com/pact-foundation/roadmap/pull/99
> feat(pact_matching): Apply generators for form urlencoded

- rust/Cargo.lock
- rust/pact_ffi/Cargo.toml
- rust/pact_ffi/src/mock_server/form_urlencoded.rs
- rust/pact_ffi/src/mock_server/handles.rs
- rust/pact_ffi/src/mock_server/mod.rs
- rust/pact_ffi/tests/tests.rs
- rust/pact_matching/Cargo.toml
- rust/pact_matching/src/generators/bodies.rs
Relates to the following RFC: https://github.com/pact-foundation/roadmap/pull/99
Depends on:
* #464
* #463
* #478
* #479
> feat: Support integration json for form urlencoded

- rust/pact_ffi/tests/tests.rs
Tests for different `date` matcher scenarios  (applicable for datetime/time as well) - 
1. when `pact:generator:type` is provided in the body matcher, mock server returns current time (Local::now()) in the provided format
2. when not provided, mock server returns the specified value
Context - Currently when using pact-js v3 matcher type `date` and `time`, mock-server returns current date/time while it's expected to return the example date/time. The issue is not originating from here (will create a seperate pr for that in pact-js), but these additional tests might worth having.
> feat(test):add tests for different date matcher scenarios in pact_ffi

- rust/pact_models/src/matchingrules/expressions.rs
This test is  for verifying that the matching expression doesn't have syntax errors. Related issue:
https://github.com/pactflow/pact-protobuf-plugin/issues/179
> test: Add test for atLeast, atMost at the beginning of the matching expression

- .github/workflows/build.yml
Instead, only trigger the 'push' step once merged into `master`.
> chore(ci): don't run on every push
